language: php

php:
  - 5.6
  - 7.0
  - 7.1

before_script:
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install --dev

script: vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover clover -v

after_success:
    - curl -sL https://bit.ly/artifact-uploader | php

